$(function(){
    if($('.top-alert').length>0){
        setTimeout(function(){
            $('.top-alert').animate({'height':'0','padding':0},2000,function(){
                $(this).hide();
            });
        },5000);
    }
});
